name: Django CI/CD
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Add SSH key
        run: |
          echo "${{ secrets.EC2_KEY }}" > ec2-key.pem
          chmod 600 ec2-key.pem

      - name: Create SSH directory
        run: |
          mkdir -p ~/.ssh
          touch ~/.ssh/known_hosts

      - name: Add EC2 host to known hosts
        run: |
          ssh-keyscan -H ${{ secrets.EC2_IP }} >> ~/.ssh/known_hosts

      - name: Deploy to Server
        run: |
          ssh -i ec2-key.pem ${{ secrets.SERVER_USER }}@${{ secrets.EC2_IP }} <<EOF
              cd /home/ec2-user/scouting-backend
              git pull https://${{ secrets.USERNAME }}:${{ secrets.TOKEN }}@github.com/Growth-Loops-Technology/scouting-backend.git main
              source ./env/bin/activate
              pip install -r requirements.txt
              # python manage.py migrate
              # lsof -ti :8006 | xargs kill -9
              # restart the process
              # nohup python manage.py runserver 0.0.0.0:8006 &
              # sudo systemctl restart gunicorn
          EOF
